sudo: required
services:
  - docker

before_install:
  - docker build -t khattri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khattri/docker-react npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "doc-react"
  env: "DocReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-051681446533"
  bucket_path: "doc-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

